#!/usr/bin/env node
/**
 * Build every generated token output from tokens/src.
 *
 *   node scripts/build-tokens.mjs            # write outputs
 *   node scripts/build-tokens.mjs --check    # exit 1 if any output would change
 *
 * Outputs (all committed):
 *   tokens/build/css/variables.css
 *   tokens/build/json/tokens.flat.json, tokens.dark.flat.json, tokens.nested.json, tokens.meta.json
 *   tokens/build/ts/tokens.ts
 *   tokens/build/react-native/theme.ts
 *   tokens/build/figma/variables.json, text-styles.json, effect-styles.json
 *   tokens/build/tailwind/preset.cjs
 *
 * Dependency-free; Node 22 or newer.
 */
import { mkdirSync, readFileSync, writeFileSync, existsSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { buildTheme, cssVarName, effectiveStatus } from "./lib/tokens.mjs";
import {
  colorToFigma,
  dimensionToNumber,
  fontFamilyToCss,
  setPath,
  stableJson,
  toTsLiteral,
  typographyToCss,
  valueToCss,
  valueToJs,
} from "./lib/format.mjs";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const CHECK = process.argv.includes("--check");
const BANNER = "Generated by scripts/build-tokens.mjs from tokens/src. Do not edit by hand; edit the source JSON and rebuild.";

const light = buildTheme(ROOT, "light");
const dark = buildTheme(ROOT, "dark");
const allErrors = [...light.errors, ...dark.errors];
if (allErrors.length) {
  console.error(allErrors.join("\n"));
  process.exit(1);
}

const same = (a, b) => JSON.stringify(a) === JSON.stringify(b);
const darkDiff = [...dark.resolved.values()].filter((t) => !same(t.resolved, light.resolved.get(t.path).resolved));

const outputs = new Map();
const emit = (relPath, content) => outputs.set(relPath, content);

// ---------------------------------------------------------------- CSS
function cssBlock(selector, tokens, indent = "") {
  const lines = [];
  for (const t of tokens) {
    const name = cssVarName(t.path);
    if (t.type === "typography") {
      const { parts, shorthand } = typographyToCss(t.resolved);
      lines.push(`${indent}  ${name}: ${shorthand};`);
      for (const [k, v] of Object.entries(parts)) lines.push(`${indent}  ${name}-${k}: ${v};`);
    } else {
      lines.push(`${indent}  ${name}: ${valueToCss(t.type, t.resolved)};`);
    }
  }
  return `${indent}${selector} {\n${lines.join("\n")}\n${indent}}`;
}

{
  const lightTokens = [...light.resolved.values()];
  const css = [
    `/* ${BANNER} */`,
    "/* Universal Profiles design tokens. Light values on :root; dark values under [data-theme=\"dark\"] and .dark; automatic dark under [data-theme=\"auto\"]. */",
    "",
    cssBlock(":root", lightTokens),
    "",
    cssBlock('[data-theme="dark"],\n.dark', darkDiff),
    "",
    "@media (prefers-color-scheme: dark) {",
    cssBlock(':root[data-theme="auto"]', darkDiff, "  "),
    "}",
    "",
  ].join("\n");
  emit("tokens/build/css/variables.css", css);
}

// ---------------------------------------------------------------- JSON
// Light records carry the declared status (the validator guarantees it never outranks the alias
// chain), so statusVia is always null there. Dark records carry the weakest status along the dark
// chain: component tokens are not re-declared in the theme file, so one that resolves through a
// proposed dark override is proposed, and statusVia names the first token along the chain that
// carries that weaker status (null when the record's own declared status already is the weakest).
const flatRecord = (theme) => (t) => {
  const effective = theme === light ? { status: t.up.status, via: null } : effectiveStatus(theme.resolved, t.path);
  return {
    path: t.path,
    type: t.type,
    value: t.resolved,
    raw: t.value,
    aliasOf: t.aliasOf,
    css: t.type === "typography" ? typographyToCss(t.resolved).shorthand : valueToCss(t.type, t.resolved),
    cssVar: cssVarName(t.path),
    description: t.description,
    status: effective.status,
    statusVia: effective.via,
    source: t.up.source,
    confidence: t.up.confidence,
    open: t.up.open ?? null,
    deprecated: !!t.deprecated,
    note: t.up.note ?? null,
  };
};
{
  const flat = [...light.resolved.values()].map(flatRecord(light));
  emit("tokens/build/json/tokens.flat.json", stableJson({ theme: "light", generated: BANNER, note: "status is the declared status; the validator requires it never to outrank the token's alias chain, so statusVia is null in this file.", count: flat.length, tokens: flat }));
  const flatDark = darkDiff.map(flatRecord(dark));
  emit("tokens/build/json/tokens.dark.flat.json", stableJson({ theme: "dark", generated: BANNER, note: "Only tokens whose value differs from the light theme. status is the weakest status along the token's dark alias chain, so a component token that resolves through a proposed dark override is reported as proposed; statusVia names the token that carries that weaker status (null when the token's own declared status is the weakest), and source stays the token's own evidence.", count: flatDark.length, tokens: flatDark }));
  const nested = {};
  for (const t of light.resolved.values()) setPath(nested, t.segments, valueToJs(t.type, t.resolved));
  const nestedDark = {};
  for (const t of darkDiff) setPath(nestedDark, t.segments, valueToJs(t.type, t.resolved));
  emit("tokens/build/json/tokens.nested.json", stableJson({ generated: BANNER, light: nested, darkOverrides: nestedDark }));

  const byStatus = {};
  const open = {};
  for (const t of light.resolved.values()) {
    byStatus[t.up.status] = (byStatus[t.up.status] ?? 0) + 1;
    if (t.up.open) (open[t.up.open] ??= []).push(t.path);
  }
  for (const t of darkDiff) {
    if (!t.up.open) continue;
    const list = (open[t.up.open] ??= []);
    if (!list.includes(t.path)) list.push(`${t.path} (dark)`);
  }
  emit(
    "tokens/build/json/tokens.meta.json",
    stableJson({
      generated: BANNER,
      version: light.metadata.version,
      counts: { total: light.resolved.size, darkOverrides: darkDiff.length, byStatus },
      openItems: Object.fromEntries(Object.entries(open).sort(([a], [b]) => a.localeCompare(b))),
      sourceFiles: light.files.map((f) => f.slice(ROOT.length + 1)),
    }),
  );
}

// ---------------------------------------------------------------- TypeScript
{
  const nested = {};
  for (const t of light.resolved.values()) setPath(nested, t.segments, valueToJs(t.type, t.resolved));
  const nestedDark = {};
  for (const t of darkDiff) setPath(nestedDark, t.segments, valueToJs(t.type, t.resolved));
  const meta = {};
  for (const t of light.resolved.values()) meta[t.path] = { type: t.type, status: t.up.status, ...(t.up.open ? { open: t.up.open } : {}), ...(t.deprecated ? { deprecated: true } : {}) };
  const paths = [...light.resolved.keys()];
  const ts = `// ${BANNER}
/* eslint-disable */

/** Token status vocabulary: observed (read from production or a cited design file), normalized (derived from observed values), proposed (new in this system, not approved), obsolete (migration only), open (placeholder awaiting a decision). */
export type TokenStatus = "observed" | "normalized" | "proposed" | "obsolete" | "open";

/** Every token path, dotted. */
export type TokenPath =
${paths.map((p) => `  | ${JSON.stringify(p)}`).join("\n")};

export interface TypographyToken {
  fontFamily: readonly string[];
  fontWeight: number;
  /** CSS px / React Native points */
  fontSize: number;
  lineHeight: number;
  letterSpacing: number;
  textTransform?: "uppercase" | "lowercase" | "capitalize" | "none";
}

export interface ShadowToken {
  color: string;
  offsetX: number;
  offsetY: number;
  blur: number;
  spread: number;
  inset?: boolean;
}

/** Resolved light-theme tokens. Dimensions and durations are numbers (px, ms); colours are CSS colour strings. */
export const tokens = ${toTsLiteral(nested)} as const;

/** Tokens whose value differs in the dark theme (same shape as \`tokens\`, partial). */
export const darkOverrides = ${toTsLiteral(nestedDark)} as const;

/** Provenance status per token path. */
export const tokenMeta: Record<TokenPath, { type: string; status: TokenStatus; open?: string; deprecated?: boolean }> = ${toTsLiteral(meta)};

/** CSS custom property name for a token path, e.g. cssVar("text.default") -> "var(--up-text-default)". */
export const cssVar = (path: TokenPath): string => \`var(--up-\${path.replace(/\\./g, "-")})\`;

export type Tokens = typeof tokens;
`;
  emit("tokens/build/ts/tokens.ts", ts);
}

// ---------------------------------------------------------------- React Native
{
  const rnFontName = (family, weight) => {
    const fam = Array.isArray(family) ? family[0] : family;
    if (fam === "PT Mono") return weight >= 700 ? "PTMonoBold" : "PTMonoRegular";
    const map = { 100: "InterThin", 200: "InterExtraLight", 300: "InterLight", 400: "InterRegular", 500: "InterMedium", 600: "InterSemiBold", 700: "InterBold", 800: "InterExtraBold", 900: "InterBlack" };
    return map[weight] ?? "InterRegular";
  };
  const pick = (prefix, theme) => {
    const out = {};
    for (const t of theme.resolved.values()) {
      if (t.segments[0] === prefix) setPath(out, t.segments.slice(1), valueToJs(t.type, t.resolved));
    }
    return out;
  };
  const semanticGroups = ["surface", "text", "border", "accent", "interactive", "status", "network", "avatar", "gradient", "glass"];
  const colorsFor = (theme) => Object.fromEntries(semanticGroups.map((g) => [g, pick(g, theme)]));
  const typography = {};
  for (const t of light.resolved.values()) {
    if (t.type !== "typography" || t.segments[0] !== "type") continue;
    const v = t.resolved;
    const role = t.segments.slice(1).join(".");
    typography[role] = {
      fontFamily: rnFontName(v.fontFamily, Number(v.fontWeight)),
      fontSize: dimensionToNumber(v.fontSize),
      lineHeight: dimensionToNumber(v.lineHeight),
      letterSpacing: v.letterSpacing ? dimensionToNumber(v.letterSpacing) : 0,
      ...(v.textTransform ? { textTransform: v.textTransform } : {}),
    };
  }
  const aliases = {};
  for (const t of light.resolved.values()) {
    if (t.segments[0] === "type-alias") aliases[t.segments[1]] = t.aliasOf.replace(/^type\./, "");
  }
  const palette = pick("color", light);
  const spacing = pick("space", light);
  const radius = pick("radius", light);
  const sizeTokens = pick("size", light);
  const opacity = pick("opacity", light);
  const blur = pick("blur", light);
  const motion = pick("motion", light);
  const identicon = pick("identicon", light);
  const darkIdenticon = pick("identicon", dark);
  const componentNames = ["button", "glass-panel", "glass-button", "glass-toggle", "glass-bar", "glass-separator", "input", "tag", "card", "screen", "profile-card", "tab-bar", "top-tabs", "header", "app-tile", "page-indicator", "sheet", "dialog", "toast", "tooltip", "skeleton", "checkbox", "radio", "switch", "slider-confirm", "qr", "list-item", "network-tag"];
  // Component tokens alias semantic roles, so their colours differ per theme: resolve them once per theme.
  const components = {};
  const darkComponents = {};
  for (const name of componentNames) {
    components[name] = pick(name, light);
    darkComponents[name] = pick(name, dark);
  }
  const shadowsRn = {};
  for (const t of light.resolved.values()) {
    if (t.type !== "shadow" || t.segments[0] !== "shadow") continue;
    const s = valueToJs("shadow", t.resolved);
    const layer = Array.isArray(s) ? s[0] : s;
    const c = layer.color;
    // split #RRGGBBAA into colour + opacity for React Native's shadow props
    let shadowColor = c;
    let shadowOpacity = 1;
    const m = c.match(/^#([0-9a-f]{6})([0-9a-f]{2})$/i);
    if (m) {
      shadowColor = `#${m[1]}`;
      shadowOpacity = Math.round((parseInt(m[2], 16) / 255) * 100) / 100;
    }
    shadowsRn[t.segments[1]] = {
      shadowColor,
      shadowOffset: { width: layer.offsetX, height: layer.offsetY },
      shadowOpacity,
      shadowRadius: layer.blur / 2,
      elevation: Math.max(1, Math.round(layer.blur / 4)),
    };
  }

  const rn = `// ${BANNER}
/* eslint-disable */
import { Platform, type TextStyle, type ViewStyle } from "react-native";

/**
 * React Native theme for Universal Profiles.
 * - \`palette\` mirrors the shape of the app's colour palette object (family -> lightness step -> hex).
 * - \`lightTheme\` and \`darkTheme\` are full themes: semantic colours, component tokens and the
 *   identicon table are resolved per theme, so read \`theme.components\` and \`theme.identicon\` rather
 *   than the light-only \`components\` and \`identicon\` exports when the theme can be dark.
 * - \`typography\` maps role names to TextStyle with the font-file names the app loads (InterRegular, PTMonoBold, ...).
 * - \`glass\` selects the platform pair for blur intensities and tints.
 */

export const palette = ${toTsLiteral(palette)} as const;

export const lightColors = ${toTsLiteral(colorsFor(light))} as const;

export const darkColors = ${toTsLiteral(colorsFor(dark))} as const;

export type ThemeColors = typeof lightColors;

export const spacing = ${toTsLiteral(spacing)} as const;
export const radius = ${toTsLiteral(radius)} as const;
export const size = ${toTsLiteral(sizeTokens)} as const;
export const opacity = ${toTsLiteral(opacity)} as const;
export const blur = ${toTsLiteral(blur)} as const;
export const motion = ${toTsLiteral(motion)} as const;

/** Identicon size table with light-theme colours; \`darkIdenticon\` carries the dark ring and fallback colours. */
export const identicon = ${toTsLiteral(identicon)} as const;

export const darkIdenticon = ${toTsLiteral(darkIdenticon)} as const;

/** Typography roles as React Native TextStyle objects. */
export const typography = ${toTsLiteral(typography)} as const satisfies Record<string, TextStyle>;

export type TypographyRole = keyof typeof typography;

/** Mobile variant name -> role, for mechanical migration of existing call sites. */
export const typographyAliases = ${toTsLiteral(aliases)} as const satisfies Record<string, TypographyRole>;

/** Component tokens resolved for the light theme. Prefer \`theme.components\`, which is this object on \`lightTheme\` and \`darkComponents\` on \`darkTheme\`. */
export const components = ${toTsLiteral(components)} as const;

/** Component tokens resolved for the dark theme (same shape as \`components\`; only colours differ). */
export const darkComponents = ${toTsLiteral(darkComponents)} as const;

/** Shadow presets translated to React Native shadow props (iOS) with an elevation hint (Android). */
export const shadows = ${toTsLiteral(shadowsRn)} as const satisfies Record<string, ViewStyle>;

/** Platform-resolved glass constants. */
export const glass = {
  panelRadius: radius["2xl"],
  cardRadius: radius.l,
  blurIntensity: Platform.OS === "android" ? blur["panel-android"] : blur["panel-ios"],
  cardBlurIntensity: Platform.OS === "android" ? blur["card-android"] : blur["card-ios"],
  tabBarBlurIntensity: Platform.OS === "android" ? blur["bar-android"] : blur["bar-ios"],
  /** Android only renders a visible blur through this experimental method. */
  experimentalBlurMethod: (Platform.OS === "android" ? "dimezisBlurView" : undefined) as "dimezisBlurView" | undefined,
  /** "light" tint brightens the whole Android screen; use "default" there. */
  blurTintLight: (Platform.OS === "android" ? "default" : "light") as "light" | "default",
  tint: (colors: ThemeColors) => (Platform.OS === "android" ? colors.surface["glass-android"] : colors.surface.glass),
  tintSolid: (colors: ThemeColors) => colors.surface["glass-solid"],
  barTint: (colors: ThemeColors) => (Platform.OS === "android" ? colors.surface["glass-bar-android"] : colors.surface["glass-bar"]),
  androidOverlay: (colors: ThemeColors) => colors.glass["android-overlay"],
  /** blurRadius for the blurred cover copy used behind full-screen glass on Android. */
  androidImageBlurRadius: blur["screen-android-image"],
} as const;

export interface Theme {
  name: "light" | "dark";
  colors: ThemeColors;
  spacing: typeof spacing;
  radius: typeof radius;
  size: typeof size;
  opacity: typeof opacity;
  motion: typeof motion;
  typography: typeof typography;
  shadows: typeof shadows;
  identicon: typeof identicon;
  components: typeof components;
}

export const lightTheme: Theme = { name: "light", colors: lightColors, spacing, radius, size, opacity, motion, typography, shadows, identicon, components };
export const darkTheme: Theme = {
  name: "dark",
  colors: darkColors as unknown as ThemeColors,
  spacing,
  radius,
  size,
  opacity,
  motion,
  typography,
  shadows,
  identicon: darkIdenticon as unknown as typeof identicon,
  components: darkComponents as unknown as typeof components,
};

/** Cap font scaling so mono names stay on one line; apply as maxFontSizeMultiplier on Text. */
export const maxFontSizeMultiplier = { default: 1.5, mono: 1.3, nav: 1.2 } as const;
`;
  emit("tokens/build/react-native/theme.ts", rn);
}

// ---------------------------------------------------------------- Tailwind overlay preset
{
  const css = (path) => `var(${cssVarName(path)})`;
  const get = (path) => light.resolved.get(path);
  const hex = (path) => get(path).resolved;
  const px = (path) => valueToCss("dimension", get(path).resolved);
  const colors = {};
  // Primitive accent family as literal values (theme-independent).
  colors.up = {};
  for (const t of light.resolved.values()) {
    if (t.segments[0] === "color" && t.segments[1] === "up" && t.segments.length === 3) colors.up[t.segments[2]] = t.resolved;
  }
  // Semantic roles through CSS custom properties so dark mode follows the document theme.
  const semantic = { surface: "surface", ink: "text", edge: "border", accent: "accent", interactive: "interactive", network: "network", avatar: "avatar" };
  for (const [key, group] of Object.entries(semantic)) {
    colors[key] = {};
    for (const t of light.resolved.values()) {
      if (t.type !== "color" || t.segments[0] !== group || t.segments.length !== 2) continue;
      colors[key][t.segments[1] === "default" ? "DEFAULT" : t.segments[1]] = css(t.path);
    }
  }
  for (const state of ["success", "error", "warning", "info"]) {
    colors[state] = {};
    for (const t of light.resolved.values()) {
      if (t.type !== "color" || t.segments[0] !== "status" || t.segments[1] !== state) continue;
      colors[state][t.segments[2]] = css(t.path);
    }
  }
  const fontSize = {};
  for (const t of light.resolved.values()) {
    if (t.type !== "typography" || t.segments[0] !== "type") continue;
    const v = t.resolved;
    const extra = { lineHeight: valueToCss("dimension", v.lineHeight), fontWeight: String(v.fontWeight) };
    if (v.letterSpacing && dimensionToNumber(v.letterSpacing) !== 0) extra.letterSpacing = valueToCss("dimension", v.letterSpacing);
    fontSize[t.segments.slice(1).join("-")] = [valueToCss("dimension", v.fontSize), extra];
  }
  const borderRadius = {};
  for (const t of light.resolved.values()) if (t.segments[0] === "radius") borderRadius[`up-${t.segments[1]}`] = px(t.path);
  const boxShadow = {};
  for (const t of light.resolved.values()) if (t.type === "shadow" && t.segments[0] === "shadow") boxShadow[`up-${t.segments[1]}`] = valueToCss("shadow", t.resolved);
  const transitionDuration = {};
  for (const t of light.resolved.values()) if (t.segments[0] === "motion" && t.segments[1] === "duration") transitionDuration[`up-${t.segments[2]}`] = valueToCss("duration", t.resolved);
  const transitionTimingFunction = {};
  for (const t of light.resolved.values()) if (t.segments[0] === "motion" && t.segments[1] === "easing") transitionTimingFunction[`up-${t.segments[2]}`] = valueToCss("cubicBezier", t.resolved);
  const opacity = {};
  for (const t of light.resolved.values()) if (t.segments[0] === "opacity") opacity[`up-${t.segments[1]}`] = String(t.resolved);
  const preset = {
    theme: {
      extend: {
        colors,
        fontFamily: { sans: get("font.family.sans").resolved, inter: get("font.family.sans").resolved, mono: get("font.family.mono").resolved },
        fontSize,
        borderRadius,
        boxShadow,
        backdropBlur: { "up-glass": `${get("blur.web").resolved}px` },
        transitionDuration,
        transitionTimingFunction,
        opacity,
        backgroundImage: {
          "up-brand-gradient": `linear-gradient(180deg, ${css("accent.gradient-start")}, ${css("accent.gradient-end")})`,
          "up-username-gradient": `linear-gradient(90deg, ${css("gradient.username-start")}, ${css("gradient.username-end")})`,
          "up-address-fallback": `linear-gradient(90deg, ${css("gradient.address-fallback-start")}, ${css("gradient.address-fallback-end")})`,
        },
        maxWidth: { "up-content": px("size.content-max-width"), "up-dialog": px("dialog.max-width-web") },
        minHeight: { "up-touch": px("size.touch-target") },
        outlineWidth: { "up-focus": px("button.focus-ring-width") },
        outlineOffset: { "up-focus": px("button.focus-ring-offset") },
      },
    },
  };
  const cjs = `// ${BANNER}
/**
 * Tailwind overlay preset for Universal Profiles.
 *
 * Compose it after the LUKSO base preset; it only extends, never replaces:
 *
 *   module.exports = {
 *     presets: [require("@lukso/web-components/tailwind.config"), require("@universal-profiles/tokens/tailwind")],
 *   };
 *
 * Semantic colours (ink, surface, edge, accent, success, ...) resolve through the CSS custom
 * properties in tokens/build/css/variables.css, so include that stylesheet and dark mode follows
 * [data-theme="dark"] or the .dark class. Because they are var() references, Tailwind opacity
 * modifiers (bg-surface-card/50) do not apply to them; use the primitive scales for that.
 * The accent family is emitted as literal values: text-up-56, bg-up-96, border-up-86.
 */
module.exports = ${toTsLiteral(preset)};
`;
  emit("tokens/build/tailwind/preset.cjs", cjs);
}

// ---------------------------------------------------------------- Figma
{
  const collections = {
    primitive: { id: "coll:primitive", name: "UP Primitives", modes: [{ id: "mode:primitive:value", name: "Value" }] },
    semantic: { id: "coll:semantic", name: "UP Semantic", modes: [{ id: "mode:semantic:light", name: "Light" }, { id: "mode:semantic:dark", name: "Dark" }] },
    component: { id: "coll:component", name: "UP Components", modes: [{ id: "mode:component:value", name: "Value" }] },
  };
  const primitiveGroups = new Set(["color", "font", "space", "size", "breakpoint", "radius", "shadow", "motion", "opacity", "blur"]);
  const semanticGroups = new Set(["surface", "text", "border", "accent", "interactive", "status", "network", "avatar", "gradient", "glass", "type"]);
  const tierOf = (t) => (primitiveGroups.has(t.segments[0]) ? "primitive" : semanticGroups.has(t.segments[0]) ? "semantic" : "component");
  const figmaType = (t) => {
    switch (t.type) {
      case "color":
        return "COLOR";
      case "dimension":
      case "duration":
      case "number":
      case "fontWeight":
        return "FLOAT";
      case "fontFamily":
      case "string":
        return "STRING";
      default:
        return null; // typography, shadow, cubicBezier -> styles, not variables
    }
  };
  const varId = (path) => `var:${path.replace(/\./g, "/")}`;
  const variables = [];
  const modeValues = [];
  const textStyles = [];
  const effectStyles = [];
  const skipped = [];
  const literal = (t, value) => {
    switch (t.type) {
      case "color":
        return colorToFigma(value);
      case "dimension":
      case "duration":
        return dimensionToNumber(value);
      case "fontFamily":
        return fontFamilyToCss(value);
      default:
        return value;
    }
  };
  const valueFor = (t, themeToken) => {
    const alias = themeToken.aliasOf;
    if (alias && light.resolved.has(alias) && figmaType(light.resolved.get(alias))) {
      return { type: "VARIABLE_ALIAS", id: varId(alias) };
    }
    const v = literal(t, themeToken.resolved);
    if (v === null || v === undefined || (typeof v === "string" && t.type === "color")) {
      return literal(t, light.resolved.get(t.path).resolved);
    }
    return v;
  };
  for (const t of light.resolved.values()) {
    const ft = figmaType(t);
    const tier = tierOf(t);
    if (!ft) {
      if (t.type === "typography" && t.segments[0] === "type") {
        const v = t.resolved;
        textStyles.push({
          name: t.segments.join("/"),
          fontFamily: Array.isArray(v.fontFamily) ? v.fontFamily[0] : v.fontFamily,
          fontWeight: Number(v.fontWeight),
          fontSize: dimensionToNumber(v.fontSize),
          lineHeight: { value: dimensionToNumber(v.lineHeight), unit: "PIXELS" },
          letterSpacing: { value: v.letterSpacing ? dimensionToNumber(v.letterSpacing) : 0, unit: "PIXELS" },
          textCase: v.textTransform === "uppercase" ? "UPPER" : "ORIGINAL",
          description: t.description,
          status: t.up.status,
        });
      } else if (t.type === "shadow" && t.segments[0] === "shadow") {
        const s = valueToJs("shadow", t.resolved);
        const layers = Array.isArray(s) ? s : [s];
        effectStyles.push({
          name: t.segments.join("/"),
          effects: layers.map((l) => ({ type: l.inset ? "INNER_SHADOW" : "DROP_SHADOW", color: colorToFigma(l.color), offset: { x: l.offsetX, y: l.offsetY }, radius: l.blur, spread: l.spread, visible: true, blendMode: "NORMAL" })),
          description: t.description,
          status: t.up.status,
        });
      } else {
        skipped.push(t.path);
      }
      continue;
    }
    if (t.type === "color" && !colorToFigma(t.resolved)) {
      skipped.push(`${t.path} (non-numeric colour "${t.resolved}")`);
      continue;
    }
    const coll = collections[tier];
    variables.push({
      action: "CREATE",
      id: varId(t.path),
      name: t.segments.join("/"),
      variableCollectionId: coll.id,
      resolvedType: ft,
      description: [t.description, `Status: ${t.up.status}.`, t.up.open ? `Open item ${t.up.open}.` : ""].filter(Boolean).join(" "),
      scopes: ["ALL_SCOPES"],
      hiddenFromPublishing: !!t.deprecated,
    });
    if (tier === "semantic") {
      modeValues.push({ variableId: varId(t.path), modeId: "mode:semantic:light", value: valueFor(t, t) });
      modeValues.push({ variableId: varId(t.path), modeId: "mode:semantic:dark", value: valueFor(t, dark.resolved.get(t.path)) });
    } else {
      modeValues.push({ variableId: varId(t.path), modeId: coll.modes[0].id, value: valueFor(t, t) });
    }
  }
  const payload = {
    generated: BANNER,
    format: "Figma REST API variables payload (POST /v1/files/{file_key}/variables). Temporary ids (coll:*, mode:*, var:*) are replaced by Figma on import. Import has not yet been exercised against a Figma file; see provenance/open-items.md OPEN-10.",
    variableCollections: Object.values(collections).map((c) => ({ action: "CREATE", id: c.id, name: c.name, initialModeId: c.modes[0].id })),
    variableModes: Object.values(collections).flatMap((c) => c.modes.map((m, i) => ({ action: i === 0 ? "UPDATE" : "CREATE", id: m.id, name: m.name, variableCollectionId: c.id }))),
    variables,
    variableModeValues: modeValues,
    skipped,
  };
  emit("tokens/build/figma/variables.json", stableJson(payload));
  emit("tokens/build/figma/text-styles.json", stableJson({ generated: BANNER, format: "One entry per typography role, shaped like Figma text style properties for a plugin or manual creation.", styles: textStyles }));
  emit("tokens/build/figma/effect-styles.json", stableJson({ generated: BANNER, format: "One entry per shadow token, shaped like Figma effect style properties.", styles: effectStyles }));
}

// ---------------------------------------------------------------- write or check
let changed = 0;
for (const [relPath, content] of outputs) {
  const abs = join(ROOT, relPath);
  const current = existsSync(abs) ? readFileSync(abs, "utf8") : null;
  if (current === content) continue;
  changed++;
  if (CHECK) {
    console.error(`stale: ${relPath}`);
  } else {
    mkdirSync(dirname(abs), { recursive: true });
    writeFileSync(abs, content);
    console.log(`wrote ${relPath}`);
  }
}
if (CHECK) {
  if (changed) {
    console.error(`${changed} generated file(s) out of date. Run: node scripts/build-tokens.mjs`);
    process.exit(1);
  }
  console.log(`tokens/build is up to date (${outputs.size} files, ${light.resolved.size} tokens, ${darkDiff.length} dark overrides)`);
} else {
  console.log(`built ${outputs.size} files (${changed} changed); ${light.resolved.size} tokens, ${darkDiff.length} dark overrides`);
}
