#!/usr/bin/env node
/**
 * Compute the designated contrast pairs (tokens/contrast-pairs.json) against the
 * resolved tokens and write accessibility/contrast-report.md.
 *
 *   node scripts/contrast-report.mjs           # write the report
 *   node scripts/contrast-report.mjs --check   # fail if the report is stale or a gated pair fails
 *
 * Exposed as a module too: `computePairs(root)` returns rows for the validator.
 */
import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { buildTheme } from "./lib/tokens.mjs";
import { contrastRatio, parseColor, composite, formatRatio } from "./lib/color.mjs";
import { readJson } from "./lib/tokens.mjs";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");

export function computePairs(root = ROOT) {
  const themes = { light: buildTheme(root, "light"), dark: buildTheme(root, "dark") };
  const spec = readJson(join(root, "tokens", "contrast-pairs.json"));
  const rows = [];
  const errors = [];
  for (const p of spec.pairs) {
    const theme = themes[p.theme];
    if (!theme) {
      errors.push(`${p.id}: unknown theme ${p.theme}`);
      continue;
    }
    const fgTok = theme.resolved.get(p.fg);
    const bgTok = theme.resolved.get(p.bg);
    if (!fgTok || !bgTok) {
      errors.push(`${p.id}: unknown token ${!fgTok ? p.fg : p.bg}`);
      continue;
    }
    const fg = parseColor(fgTok.resolved);
    let bg = parseColor(bgTok.resolved);
    if (!fg || !bg) {
      errors.push(`${p.id}: unparseable colour (${fgTok.resolved} / ${bgTok.resolved})`);
      continue;
    }
    let baseNote = "";
    if (p.base) {
      const base = parseColor(p.base);
      bg = composite(bg, base);
      baseNote = ` over ${p.base}`;
    } else if (bg.a < 1) {
      // translucent backgrounds without an explicit base composite over the theme canvas
      const canvas = parseColor(theme.resolved.get("surface.canvas").resolved);
      bg = composite(bg, canvas);
      baseNote = " over surface.canvas";
    }
    const ratio = contrastRatio(fg, bg);
    const pass = p.min == null ? true : ratio >= p.min;
    rows.push({ ...p, fgValue: fgTok.resolved, bgValue: bgTok.resolved, baseNote, ratio, pass });
    if (!pass && !p.informational) errors.push(`${p.id}: ${p.fg} on ${p.bg}${baseNote} = ${formatRatio(ratio)} < ${p.min}:1 (${p.context})`);
  }
  return { rows, errors };
}

export function renderReport(rows) {
  const lines = [
    "# Contrast report",
    "",
    "Generated by `scripts/contrast-report.mjs` from `tokens/contrast-pairs.json` and the resolved tokens. Do not edit by hand.",
    "",
    "Ratios follow WCAG 2.2. Gates: 4.5:1 for text, 3:1 for large text and non-text indicators. Translucent backgrounds are composited over the listed base colour. Informational rows document known limits and do not gate validation.",
    "",
  ];
  const gated = rows.filter((r) => !r.informational);
  const failing = gated.filter((r) => !r.pass);
  lines.push(`Summary: ${gated.length} gated pairs, ${gated.length - failing.length} pass, ${failing.length} fail; ${rows.length - gated.length} informational rows.`, "");
  for (const theme of ["light", "dark"]) {
    lines.push(`## ${theme[0].toUpperCase()}${theme.slice(1)} theme`, "");
    lines.push("| Id | Foreground | Background | Ratio | Min | Result | Context |", "|---|---|---|---|---|---|---|");
    for (const r of rows.filter((x) => x.theme === theme)) {
      const result = r.informational ? (r.pass ? "info (pass)" : "info (below)") : r.pass ? "pass" : "FAIL";
      lines.push(`| ${r.id} | \`${r.fg}\` ${r.fgValue} | \`${r.bg}\` ${r.bgValue}${r.baseNote} | ${formatRatio(r.ratio)} | ${r.min ?? "-"}:1 | ${result} | ${r.context} |`);
    }
    lines.push("");
  }
  return lines.join("\n");
}

const isMain = process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1];
if (isMain) {
  const check = process.argv.includes("--check");
  const { rows, errors } = computePairs(ROOT);
  const report = renderReport(rows);
  const out = join(ROOT, "accessibility", "contrast-report.md");
  const current = existsSync(out) ? readFileSync(out, "utf8") : null;
  if (errors.length) {
    console.error(errors.join("\n"));
  }
  if (check) {
    if (current !== report) {
      console.error("stale: accessibility/contrast-report.md (run node scripts/contrast-report.mjs)");
      process.exit(1);
    }
    if (errors.length) process.exit(1);
    console.log(`contrast report up to date: ${rows.length} pairs checked`);
  } else {
    writeFileSync(out, report);
    console.log(`wrote accessibility/contrast-report.md (${rows.length} pairs, ${errors.length} failing)`);
    if (errors.length) process.exit(1);
  }
}
